projects:
  cfdbadmintonweb:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        graphQLApiId: 2oax566najelpm463zldhra4r4
        codeGenTarget: typescript
        generatedFileName: src/badminton-api.ts
        docsFilePath: src/graphql
        region: eu-central-1
      endpoints:
        prod: >-
          https://nfgxtncwivenfdw3m66rfxleay.appsync-api.eu-central-1.amazonaws.com/graphql
