// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "eu-central-1",
    "aws_content_delivery_bucket": "cfdbadmintonweb-20181208232240-hostingbucket",
    "aws_content_delivery_bucket_region": "eu-central-1",
    "aws_content_delivery_url": "http://cfdbadmintonweb-20181208232240-hostingbucket.s3-website.eu-central-1.amazonaws.com",
    "aws_cognito_identity_pool_id": "eu-central-1:36f2611f-6a8c-4e94-b69f-238ee252b122",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_b3ZGS36Cl",
    "aws_user_pools_web_client_id": "2naif3bk6ais02aj30nubu6k6k",
    "aws_appsync_graphqlEndpoint": "https://nfgxtncwivenfdw3m66rfxleay.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
