// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "eu-central-1",
    "aws_content_delivery_bucket": "cfdbadminton",
    "aws_content_delivery_bucket_region": "eu-central-1",
    "aws_content_delivery_url": "http://cfdbadminton.s3-website.eu-central-1.amazonaws.com",
    "aws_appsync_graphqlEndpoint": "https://nfgxtncwivenfdw3m66rfxleay.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cognito_identity_pool_id": "eu-central-1:10aa460b-d703-42cd-bea2-a894eccb25b5",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_zBCONNtGE",
    "aws_user_pools_web_client_id": "11t50ridbvvch813mscd0b33p2"
};


export default awsmobile;
